### ISSUE TITLE
Research physics in Unity

### ISSUE THREAD

**Issue by DShamaev** [DShamaev/UnityBegginerProject#11]
1. Read information about physics
2. Prepare small Unity examples with simple physics interaction (based on 2d top map)
3. Prepare speech and share info with others

**Comment by Vurfen** [comment]
![1](https://cloud.githubusercontent.com/assets/10715062/6093681/d8b8a8d8-af11-11e4-9f89-588936f17457.JPG)
how you can add Physics

**Comment by Mixaill** [comment]
Moved to wiki https://github.com/DShamaev/UnityBegginerProject/wiki/Physics-basics
