### ISSUE TITLE
Add background

### ISSUE THREAD

**Issue by DShamaev** [DShamaev/UnityBegginerProject#2]
1. choose background image
2. add background in unity project
3. push to repository

**Comment by Mixaill** [comment]
Should this background be parallax?
I found some tips about parallax background on answers.unity3d.com

http://answers.unity3d.com/questions/37974/2d-parallax-background.html
http://answers.unity3d.com/questions/28546/how-to-copy-camera-rotation-plus-custom-setup-for.html

**Comment by Vurfen** [comment]
done

**Comment by Mixaill** [comment]
Don't think so.

**Comment by Mixaill** [comment]
Superseded by #12
