### ISSUE TITLE
tasks for day 2

### ISSUE THREAD

**Issue by DShamaev** [DShamaev/UnityBegginerProject#5]
1. We need to find out how to determine min/max values of screen coords.
2. We need to find out how to add new game objects to scene

**Comment by Mixaill** [comment]
1. частично исправлено в 9239a1dfb63c1320c96dbb6a994eada2b56b4179
2. частично исправлено в 815d1e1e06d32fd9b1c47b3a5fb7d963b0b9f9b9 и 2b3b790609612e45eb6aca452e531a9b62f88833 . Также, смотри багу #6
